import type {
  LedgerEntry,
  FeelingEntry,
  LookEntry,
  TasteEntry,
  WeeklyReview,
  MonthlyReflection,
  StableTemplate,
  ToTryEntry,
  IdentityNote,
} from "./types";
import { getProgramWeekBounds } from "./program-week";

export const ledgerEntries: LedgerEntry[] = [
  {
    id: "l1",
    title: "Soft structure blazer for lunch meetings",
    date: "2025-03-05",
    category: "Fashion",
    amount: 420,
    purpose: "One piece that works for client lunches without feeling costumey",
    effectiveness: "High",
    repurchase: "Yes",
    notes: "The cut is forgiving, fabric holds shape. Felt more like myself in quiet tailoring.",
  },
  {
    id: "l2",
    title: "Jaw botox follow-up",
    date: "2025-03-02",
    category: "Aesthetic",
    amount: 1800,
    purpose: "Maintain subtle definition, not frozen",
    effectiveness: "High",
    repurchase: "Yes",
    notes: "Same doctor. Still learning what softness actually means on me.",
  },
  {
    id: "l3",
    title: "Hydrating serum — the one with niacinamide",
    date: "2025-02-28",
    category: "Skincare",
    amount: 280,
    purpose: "Even out texture and reduce morning redness",
    effectiveness: "Medium",
    repurchase: "Maybe",
    notes: "Gentle. Not a wow, but consistent.",
  },
  {
    id: "l4",
    title: "Salon cut + low-maintenance layers",
    date: "2025-02-22",
    category: "Hair",
    amount: 380,
    purpose: "Less styling time, more good-hair days",
    effectiveness: "High",
    repurchase: "Yes",
    notes: "Finally found someone who gets 'effortless but put-together'.",
  },
  {
    id: "l5",
    title: "Pilates reformer class pack",
    date: "2025-02-15",
    category: "Wellness",
    amount: 1200,
    purpose: "Posture and core, not weight loss",
    effectiveness: "High",
    repurchase: "Yes",
    notes: "Body feels longer. Clothes sit better.",
  },
  {
    id: "l6",
    title: "Exhibition ticket + catalogue",
    date: "2025-03-07",
    category: "Experience",
    amount: 120,
    purpose: "Feed the eye, not the algorithm",
    effectiveness: "High",
    repurchase: "Yes",
    notes: "The green-and-grey palette stuck. Want to try it in outfit.",
  },
  {
    id: "l7",
    title: "Trendy bag that looked better online",
    date: "2025-02-10",
    category: "Fashion",
    amount: 650,
    purpose: "Thought it would elevate casual looks",
    effectiveness: "Low",
    repurchase: "No",
    notes: "Too polished but not alive. Sold it.",
  },
  {
    id: "l8",
    title: "Facial — deep hydration",
    date: "2025-03-01",
    category: "Skincare",
    amount: 580,
    purpose: "Reset after travel and stress",
    effectiveness: "High",
    repurchase: "Yes",
  },
];

export const feelingEntries: FeelingEntry[] = [
  {
    id: "f1",
    title: "Saturday slow",
    date: "2025-03-08",
    mood: ["Calm", "Happy"],
    energy: 4,
    self_state: "Like a blanket that’s been in the sun — warm, soft, present.",
    favorite_moment: "Standing in front of that one painting. Green and grey. Nothing to do but look.",
    uncomfortable_moment: "Spent 20 minutes deciding what to wear. Still not great at low-stakes outfit decisions.",
    touched_by: "How little it took to feel like myself today: good light, one good piece, no performance.",
    confirmed: "I prefer small exhibitions. Crowds drain the meaning.",
    eliminated: "Said no to a dinner I didn’t want. No guilt.",
  },
  {
    id: "f2",
    title: "Midweek clarity",
    date: "2025-03-06",
    mood: ["Peaceful", "Hopeful"],
    energy: 3,
    self_state: "Quietly capable. Not loud confident — the kind that shows up and does the thing.",
    favorite_moment: "Client said they felt at ease. That’s the feedback I care about.",
    uncomfortable_moment: "Morning rush. Skipped proper breakfast. Felt it by 11.",
    touched_by: "A sentence in the book I’m reading: 'Elegance is refusal.'",
    confirmed: "Restraint in outfit = less decision fatigue. More energy for the actual day.",
    eliminated: "Scrolling before bed. Not fully gone but catching myself.",
  },
  {
    id: "f3",
    title: "Tired but clear",
    date: "2025-03-04",
    mood: ["Tired", "Calm"],
    energy: 2,
    self_state: "Like I’m running at 70%. But 70% today was enough.",
    favorite_moment: "Put on the new blazer. Didn’t overthink. Felt like a uniform that fits.",
    uncomfortable_moment: "Comparison thought: someone else’s feed, someone else’s pace. Let it go.",
    touched_by: "The Row-like restraint in a look I saw. Not copying — recognising what I’m drawn to.",
    confirmed: "Low energy days need a go-to template. Still building mine.",
    eliminated: "Saying yes to an extra call. Next time I’ll protect the block.",
  },
  {
    id: "f4",
    title: "Sunday reset",
    date: "2025-03-02",
    mood: ["Peaceful", "Happy"],
    energy: 4,
    self_state: "Soft reset. Not productivity, just being.",
    favorite_moment: "Skincare routine without rushing. Small luxury.",
    uncomfortable_moment: "None worth noting. Gentle day.",
    touched_by: "Light through the window. Simple.",
    confirmed: "I need one day a week with no agenda.",
    eliminated: "—",
  },
  {
    id: "f5",
    title: "Anxious then grounded",
    date: "2025-02-28",
    mood: ["Anxious", "Calm"],
    energy: 3,
    self_state: "Started scattered. Ended more grounded after writing this.",
    favorite_moment: "Walking home. Cold air. Felt in my body again.",
    uncomfortable_moment: "Morning spiral about a small work thing. Disproportionate.",
    touched_by: "A friend’s text: 'You don’t have to be perfect to be good.'",
    confirmed: "Writing down the feeling helps. This system is for that.",
    eliminated: "Checking email after 9pm. One day at a time.",
  },
  {
    id: "f6",
    title: "High energy creative",
    date: "2025-02-25",
    mood: ["Energized", "Hopeful"],
    energy: 5,
    self_state: "Ideas flowing. Body and mind aligned.",
    favorite_moment: "Solved a problem in the shower. Classic.",
    uncomfortable_moment: "Brief crash after lunch. Noted: need lighter midday meals.",
    touched_by: "A space I walked past — minimal, warm wood, one plant. Want to remember that.",
    confirmed: "When energy is high, I make better style and life decisions. Protect the source.",
    eliminated: "—",
  },
];

const PLACEHOLDER_IMAGE = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&h=500&fit=crop";

export const lookEntries: LookEntry[] = [
  {
    id: "lo1",
    title: "Weekend exhibition look",
    date: "2025-03-08",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Social",
    styleTags: ["Minimal", "Relaxed", "Editorial"],
    colorPalette: "Warm neutrals, soft beige",
    selfRating: 4,
    photogenicRating: "Okay",
    notes: "Felt like me. Not trying too hard.",
    hairstyle: "Low ponytail, face-framing pieces",
    makeup: "Light base, terracotta lip",
    feedback: "Friend said it looked 'effortless'.",
    nextAdjustment: "Try same formula in grey-green after that exhibition.",
  },
  {
    id: "lo2",
    title: "Client lunch — soft structure",
    date: "2025-03-05",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Work",
    styleTags: ["Smart casual", "Tailored", "Quiet"],
    colorPalette: "Black, cream, one gold accent",
    selfRating: 5,
    photogenicRating: "Strong",
    notes: "The blazer did the work. Felt professional without stiff.",
    hairstyle: "Sleek low bun",
    makeup: "Clean skin, defined brow, nude lip",
    feedback: "Client commented on looking put-together. Good.",
    nextAdjustment: "Repeat. This is a template.",
  },
  {
    id: "lo3",
    title: "Low-energy rescue",
    date: "2025-03-04",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Daily",
    styleTags: ["Comfort", "Minimal", "Cozy"],
    colorPalette: "Grey, white, soft brown",
    selfRating: 3,
    photogenicRating: "N/A",
    notes: "Didn’t love it but it was appropriate. Need a better low-energy formula.",
    hairstyle: "Air-dried, loose",
    makeup: "Tinted moisturiser, lip balm only",
    nextAdjustment: "Define a proper low-energy template so I don’t default to 'whatever'.",
  },
  {
    id: "lo4",
    title: "Dinner with friends",
    date: "2025-03-01",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Social",
    styleTags: ["Feminine", "Soft", "Evening"],
    colorPalette: "Dusty rose, cream",
    selfRating: 4,
    photogenicRating: "Okay",
    notes: "Felt pretty without overdone.",
    hairstyle: "Soft waves, side part",
    makeup: "Soft smoky eye, rose lip",
    feedback: "Got a few compliments. Felt natural.",
  },
  {
    id: "lo5",
    title: "Quick errands",
    date: "2025-02-28",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Daily",
    styleTags: ["Casual", "Minimal"],
    colorPalette: "Black, denim blue",
    selfRating: 3,
    photogenicRating: "N/A",
    notes: "Functional. Not memorable. Fine for the day.",
  },
  {
    id: "lo6",
    title: "Presentation day",
    date: "2025-02-25",
    imageUrl: PLACEHOLDER_IMAGE,
    occasion: "Work",
    styleTags: ["Professional", "Structured", "Confident"],
    colorPalette: "Navy, white",
    selfRating: 5,
    photogenicRating: "Strong",
    notes: "Wanted to feel sharp. Did. Will reuse this formula.",
    hairstyle: "Neat ponytail",
    makeup: "Full but subtle. Focus on eyes.",
  },
];

export const tasteEntries: TasteEntry[] = [
  {
    id: "t1",
    title: "Past Lives",
    type: "Movie",
    date: "2025-03-01",
    whyILikeIt: "Quiet. No melodrama. The way silence and restraint said more than dialogue. Colour palette — muted, natural — stayed with me.",
    translateToLife: "Less explaining. More trusting the space between. In outfit: fewer pieces, better quality. In presence: calm over performative.",
    tags: ["Restraint", "Colour", "Emotion"],
  },
  {
    id: "t2",
    title: "The Row — overall aesthetic",
    type: "Brand",
    date: "2025-02-28",
    whyILikeIt: "The row-like restraint. Nothing loud. Fabric, cut, proportion. Luxury that doesn’t need to announce itself.",
    translateToLife: "When in doubt, remove one thing. Neutral palette as base. Invest in one great coat, one great bag, rather than many 'cute' pieces.",
    tags: ["Minimal", "Luxury", "Proportion"],
  },
  {
    id: "t3",
    title: "Olafur Eliasson exhibition",
    type: "Exhibition",
    date: "2025-03-07",
    whyILikeIt: "Light and colour as experience. Green and grey gradients. Felt both calm and alert.",
    translateToLife: "Try grey-green in outfit. One piece in that tone. Also: how light hits the face — worth considering in makeup and hair.",
    tags: ["Light", "Colour", "Space"],
  },
  {
    id: "t4",
    title: "The Luminous Novel",
    type: "Book",
    date: "2025-02-20",
    whyILikeIt: "Long, meandering, thoughtful. No rush. The sentence 'Elegance is refusal' — wrote it down.",
    translateToLife: "Refusal as practice: say no to one extra thing per day. In style: refuse the trend that doesn’t fit. In calendar: refuse the meeting that could be a message.",
    tags: ["Elegance", "Pace", "Refusal"],
  },
  {
    id: "t5",
    title: "That café on the corner",
    type: "Space",
    date: "2025-02-15",
    whyILikeIt: "Warm wood, one big plant, soft light. No clutter. Felt like I could think.",
    translateToLife: "Home: one clear surface. One plant. One good lamp. Same principle — calm, intentional, not full.",
    tags: ["Space", "Minimal", "Warmth"],
  },
  {
    id: "t6",
    title: "Charlotte Gainsbourg — style and presence",
    type: "Person",
    date: "2025-02-10",
    whyILikeIt: "Never overdone. Slightly undone. Intelligent, not cute. Ageing with grace — not fighting it, not giving up.",
    translateToLife: "Aim for 'slightly undone' rather than 'perfect'. One piece slightly relaxed. Hair not too polished. It’s a look that scales.",
    tags: ["Undone", "Intelligence", "Grace"],
  },
];

function buildProgramWeekReviews(): WeeklyReview[] {
  return Array.from({ length: 52 }, (_, i) => {
    const programWeek = i + 1;
    const { weekStart, weekEnd } = getProgramWeekBounds(programWeek);
    return {
      id: `w${programWeek}`,
      programWeek,
      weekStart,
      weekEnd,
    };
  });
}

/** 52 个自然周；第 1 周为 2026-03-02～2026-03-08，与方案周次对齐。 */
export const weeklyReviews: WeeklyReview[] = buildProgramWeekReviews();

export const monthlyReflections: MonthlyReflection[] = [
  {
    id: "m1",
    month: "March 2025",
    monthDate: "2025-03-01",
    keyword: ["Restraint", "Quiet", "Palette"],
    biggestChange: "Started actually using this system. Writing feelings and looks. Patterns are becoming visible.",
    top3WorthIt: [
      "Jaw botox follow-up — subtle, consistent.",
      "Soft structure blazer — already a go-to.",
      "Exhibition + catalogue — inspired the grey-green direction.",
    ],
    top3NotWorthIt: [
      "The trendy bag — sold. Too polished, not me.",
      "One impulse skincare buy — not bad, just unnecessary.",
      "A dinner I said yes to out of obligation — energy drain.",
    ],
    bestLooks: ["Client lunch — soft structure", "Weekend exhibition look"],
    bestInspirations: ["Olafur Eliasson exhibition", "The Row aesthetic", "Past Lives"],
    nextMonthFocus: "Lock in 2–3 stable templates (client, daily, low-energy). Reduce decision fatigue. One grey-green outfit. Protect sleep.",
  },
  {
    id: "m2",
    month: "February 2025",
    monthDate: "2025-02-01",
    keyword: ["Foundation", "Movement", "Clarity"],
    biggestChange: "Invested in posture (Pilates) and one good haircut. Both paid off.",
    top3WorthIt: [
      "Pilates pack — body and clothes both better.",
      "Hair cut + layers — less fuss, more good days.",
      "The Luminous Novel — 'elegance is refusal' stuck.",
    ],
    top3NotWorthIt: [
      "A few small online buys that didn’t fit the wardrobe.",
      "Skipping rest days.",
    ],
    bestLooks: ["Presentation day", "Dinner with friends"],
    bestInspirations: ["The Row", "Charlotte Gainsbourg", "That café space"],
    nextMonthFocus: "Build the habit of logging. Define what 'my kind of elegance' means in practice. One stable work look.",
  },
];

export const stableTemplates: StableTemplate[] = [
  {
    id: "st1",
    name: "Client meeting look",
    scenario: "Lunch or meeting with clients. Need to feel professional, approachable, not stiff.",
    keyPieces: "Soft structure blazer (cream or black), simple top, tailored trousers or midi skirt. Low bun or sleek ponytail. Clean skin, defined brow, nude lip.",
    whyItWorks: "One strong piece does the work. Rest is quiet. I feel like myself, not in costume. Client feedback has been positive.",
    usageCount: 4,
  },
  {
    id: "st2",
    name: "Daily uniform (in progress)",
    scenario: "WFH or low-stakes day. Want to feel put-together without effort.",
    keyPieces: "Oversized knit or soft shirt, straight-leg trousers or jeans. Hair: air-dried or low pony. Minimal makeup — tinted moisturiser, lip balm.",
    whyItWorks: "Comfort first, but with one element that feels intentional. Still refining.",
    usageCount: 2,
  },
  {
    id: "st3",
    name: "Low-energy rescue",
    scenario: "Tired or off day. Need to look acceptable without draining myself.",
    keyPieces: "TBD. Currently defaulting to whatever’s clean. Goal: one go-to (e.g. all black, one good jumper, no decisions).",
    whyItWorks: "Not yet defined. This is the next template to build.",
  },
  {
    id: "st4",
    name: "Quick outing",
    scenario: "Errands, coffee, casual catch-up.",
    keyPieces: "One good coat, simple top, jeans or trousers. Same bag. Hair: quick tie or cap. Minimal makeup.",
    whyItWorks: "Speed. Fewer choices. One coat elevates everything.",
  },
  {
    id: "st5",
    name: "Exhibition / cultural",
    scenario: "Gallery, talk, or something that feeds the eye. Want to feel present, not overdressed.",
    keyPieces: "Neutral palette. One interesting texture or cut. Comfortable shoes. Soft hair. Light makeup — focus on skin and one feature.",
    whyItWorks: "Fits the context. I can focus on the experience, not my outfit. The grey-green idea from last exhibition is next to try.",
  },
  {
    id: "st6",
    name: "Soft formal",
    scenario: "Dinner, event, or occasion that asks for 'dressed up' but not black-tie.",
    keyPieces: "Midi dress or tailored separates. Dusty or soft colour. One good bag, simple jewellery. Hair: soft waves or up. Makeup: one statement (lip or eye), rest clean.",
    whyItWorks: "Feminine without fussy. Photographs well. Feels like me.",
    usageCount: 3,
  },
];

export const toTryEntries: ToTryEntry[] = [
  {
    id: "tt1",
    title: "Grey-green outfit (from exhibition)",
    type: "Style",
    status: "Want to try",
    priority: "High",
    whyWantToTry: "The Olafur show palette stuck. Want to wear it — one piece in that tone, see how it feels on me.",
  },
  {
    id: "tt2",
    title: "Blunt collarbone-length cut",
    type: "Hairstyle",
    status: "Planned",
    priority: "Medium",
    budget: "~400",
    whyWantToTry: "Current layers work but want to try something sharper. Need a reference photo that’s not too trendy.",
  },
  {
    id: "tt3",
    title: "One good gold hoop",
    type: "Item",
    status: "Want to try",
    priority: "Medium",
    budget: "200–400",
    whyWantToTry: "Minimal daily jewellery. The Row / quiet luxury vibe. One pair that goes with everything.",
  },
  {
    id: "tt4",
    title: "Terracotta / burnt sienna lip",
    type: "Makeup",
    status: "Tried",
    priority: "Low",
    whyWantToTry: "Tried it on weekend look. Liked it. Want to make it a default option.",
  },
  {
    id: "tt5",
    title: "That new gallery in X district",
    type: "Place",
    status: "Want to try",
    priority: "Low",
    whyWantToTry: "Friend said the space is beautiful. Good for a slow Saturday.",
  },
  {
    id: "tt6",
    title: "Sound bath / meditation session",
    type: "Experience",
    status: "Planned",
    priority: "Medium",
    whyWantToTry: "Want to see if it helps with sleep and reset. One trial session.",
  },
  {
    id: "tt7",
    title: "Wide-leg wool trousers",
    type: "Item",
    status: "Want to try",
    priority: "High",
    budget: "300–600",
    whyWantToTry: "Would complete the client look. Need to try in person for length and fit.",
  },
  {
    id: "tt8",
    title: "Old trend I almost bought into",
    type: "Style",
    status: "Archived",
    priority: "Low",
    whyWantToTry: "Decided it wasn’t me. Archived so I remember not to revisit.",
  },
];

export const identityNotes: IdentityNote[] = [
  {
    id: "id1",
    section: "woman_i_want_to_become",
    title: "The woman I want to become",
    content:
      "Someone who is clear without being cold. Who dresses for herself first — not for the algorithm or the room. Who moves through the world with quiet confidence: less explaining, more being. Who ages with curiosity, not fear. Who has a point of view on beauty and taste that is hers, not borrowed.",
    updatedAt: "2025-03-01",
  },
  {
    id: "id2",
    section: "first_glance",
    title: "What I want people to feel at first glance",
    content:
      "Put-together but not stiff. Approachable. Like I have my act together without needing to prove it. A sense of calm and intention. Not 'trendy' — more 'she knows what works for her.'",
    updatedAt: "2025-02-28",
  },
  {
    id: "id3",
    section: "my_elegance",
    title: "What “my kind of elegance” means",
    content:
      "Restraint. Fewer pieces, better quality. Neutral base with one intentional detail. Fabric and cut over logo. Quiet luxury: it doesn’t need to announce itself. Comfort that doesn’t look sloppy. The Row-like clarity, but adapted to my life and budget. Elegance is refusal — I’m learning to refuse the wrong things.",
    updatedAt: "2025-03-05",
  },
  {
    id: "id4",
    section: "no_longer_want",
    title: "What I no longer want to be",
    content:
      "The person who buys because it’s trending. Who dresses for others’ approval. Who piles on because more feels safer. Who is too polished but not alive. Who says yes when she means no. Who confuses busy with meaningful.",
    updatedAt: "2025-02-20",
  },
  {
    id: "id5",
    section: "style_keywords",
    title: "Personal style keywords",
    content:
      "Minimal. Soft structure. Quiet. Neutral palette (with room for grey-green, dusty rose, cream). Tailored but not stiff. Feminine without fussy. One good piece that does the work. Slightly undone. Quality over quantity. Refusal.",
    updatedAt: "2025-03-06",
  },
  {
    id: "id6",
    section: "notes",
    title: "Notes on beauty, money, taste, and selfhood",
    content:
      "Beauty: It’s not about fixing. It’s about becoming. Skincare, hair, posture — they’re part of the system. But the goal is feeling like myself, not looking like someone else.\n\nMoney: I’m willing to invest in things that reduce decision fatigue and last. One great blazer > five okay ones. Experiences (exhibitions, good meals) feed the system. Impulse buys don’t.\n\nTaste: It’s built slowly. I’m collecting references — films, spaces, people — and asking: what can I translate? Not copy. Translate.\n\nSelfhood: This system is for noticing. What works. What doesn’t. What I’m confirming. What I’m eliminating. So that by the end of the year, I have a methodology — not just a wardrobe.",
    updatedAt: "2025-03-08",
  },
];

// Dashboard aggregates
export const dashboardStats = {
  monthlySpend: 3780,
  monthlyEntryCount: 12,
  monthlyBestLookCount: 2,
  monthlyHighEnergyDays: 8,
};

export const weeklyFocus = {
  theme: "Quiet structure",
  microAdjustments: [
    "Try one outfit in grey-green (from the exhibition).",
    "Write down the 'client lunch' look as a stable template.",
    "One evening with no screens after 9.",
  ],
  keywords: ["Restraint", "Quiet", "Palette"],
};
