/** Nicole 52 周个人形象与审美系统 — 结构来自定制方案 PDF */

export interface Week52Phase {
  id: string;
  nameZh: string;
  nameEn: string;
  weekStart: number;
  weekEnd: number;
}

export interface Week52Entry {
  week: number;
  phaseId: string;
  titleZh: string;
  titleEn: string;
  goalZh: string;
  /** 本周可执行要点（从方案「详细内容」提炼） */
  tasksZh: string[];
}

export const WEEK52_PHASES: Week52Phase[] = [
  { id: "p1", nameZh: "内核打底 · 形象与审美筑基", nameEn: "Core & image foundation", weekStart: 1, weekEnd: 8 },
  { id: "p2", nameZh: "消费认知 · 生活美学入门", nameEn: "Consumption & life aesthetics", weekStart: 9, weekEnd: 12 },
  { id: "p3", nameZh: "个人 IP · 心理内核", nameEn: "Personal IP & psychology", weekStart: 13, weekEnd: 16 },
  { id: "p4", nameZh: "复训巩固 · 文化心性入门", nameEn: "Review & culture", weekStart: 17, weekEnd: 20 },
  { id: "p5", nameZh: "修行文旅 · 影像美学", nameEn: "Retreat & imaging", weekStart: 21, weekEnd: 24 },
  { id: "p6", nameZh: "阅读 · 观影 · 播客", nameEn: "Reading, film & podcasts", weekStart: 25, weekEnd: 28 },
  { id: "p7", nameZh: "社交 · 礼仪 · 情商", nameEn: "Social & etiquette", weekStart: 29, weekEnd: 32 },
  { id: "p8", nameZh: "花艺 · 形体 · 冥想", nameEn: "Floral, body & meditation", weekStart: 33, weekEnd: 36 },
  { id: "p9", nameZh: "古琴 · 香道", nameEn: "Guqin & incense", weekStart: 37, weekEnd: 40 },
  { id: "p10", nameZh: "情感 · 共情与链接", nameEn: "Emotion & connection", weekStart: 41, weekEnd: 44 },
  { id: "p11", nameZh: "高阶成长 · 全年闭环", nameEn: "Advanced & closure", weekStart: 45, weekEnd: 52 },
];

export const WEEK52_ENTRIES: Week52Entry[] = [
  {
    week: 1,
    phaseId: "p1",
    titleZh: "风格探索 + 逛街实操",
    titleEn: "Style exploration & shopping",
    goalZh:
      "无压力感知适合自身的穿搭风格，消除穿搭恐惧；完成身形与肤色诊断，建立科学穿搭认知。",
    tasksZh: [
      "高端商圈 / 买手店 / 轻奢集合店沉浸式体验",
      "试穿不同廓形、长度、材质、色系并记录最优方案",
      "肤色冷暖与身形分析，建立「适合清单」「避雷清单」",
      "梳理创始人身份穿搭底线与高级感标准",
    ],
  },
  {
    week: 2,
    phaseId: "p1",
    titleZh: "13 套全场景穿搭 + 饰品",
    titleEn: "13 outfits & accessories",
    goalZh: "一次性落地全年高频场景穿搭，形成可复制、不费力的穿搭系统；明确预算与采购方向。",
    tasksZh: [
      "职业装 5 套 + 饰品：商务、面谈、会议、演讲、正式亮相",
      "生活装 3 套 + 饰品：日常、社交、周末、短途、轻松聚会",
      "社交装 3 套 + 饰品：约会、晚宴、小聚、精致出行",
      "睡衣 2 套、内衣组合；输出搭配逻辑与衣橱收纳思路",
    ],
  },
  {
    week: 3,
    phaseId: "p1",
    titleZh: "妆容系统 + 皮肤管理",
    titleEn: "Makeup & skincare",
    goalZh: "掌握日常极简快速妆容，建立科学护肤逻辑，改善油脂、毛孔、暗沉与状态不稳。",
    tasksZh: [
      "1V1 面诊：五官比例、眉眼唇优势、脸型风格",
      "5 分钟日常妆 + 10 分钟社交妆流程",
      "底妆、眉、眼、唇、修容实操",
      "定制早晚护肤、控油与维稳方案；筛品避坑",
    ],
  },
  {
    week: 4,
    phaseId: "p1",
    titleZh: "发型定制 + 颜值微调",
    titleEn: "Hair & refinement",
    goalZh: "优化轮廓与精致度，降低打理成本，打造持久、高级、适配身份的发型与五官状态。",
    tasksZh: [
      "按脸型、气质、职业定制发型",
      "半永久眉形；可选纹眼线强化眼神",
      "3 款快速发型：低马尾、半扎发、慵懒卷",
      "蓬松、持久、显脸小、易打理技巧",
    ],
  },
  {
    week: 5,
    phaseId: "p1",
    titleZh: "艺术展沉浸式学习",
    titleEn: "Exhibition immersion",
    goalZh: "学会看懂展；建立色彩、线条、结构、材质认知；能转化到穿搭与生活美学。",
    tasksZh: [
      "当季高品质艺术展 / 设计展 / 时装展",
      "陪同讲解色彩、构图、材质与空间氛围",
      "拆解艺术元素到穿搭、家居、妆容、气质",
      "练习拍照构图与审美笔记；建初级灵感库",
    ],
  },
  {
    week: 6,
    phaseId: "p1",
    titleZh: "买手店深度探究 + 消费认知",
    titleEn: "Buyers & consumption",
    goalZh: "重构理性消费观，精准购物；告别买贵不买对、为买而买。",
    tasksZh: [
      "面料、剪裁、做工、版型鉴别",
      "价值、质感、耐用性、搭配率分析",
      "建立「适合、可重复穿、有质感、低浪费」逻辑",
      "控制冲动与闲置消费",
    ],
  },
  {
    week: 7,
    phaseId: "p1",
    titleZh: "前期内容复训巩固",
    titleEn: "Review weeks 1–6",
    goalZh: "强化穿搭、妆容、发型、审美基础，查漏补缺，确保落地。",
    tasksZh: [
      "穿搭快速搭配与场景模拟",
      "妆容速度与持久度练习",
      "发型日常化与懒人技巧",
      "审美判断强化与一对一纠正",
    ],
  },
  {
    week: 8,
    phaseId: "p1",
    titleZh: "实践复盘 + 作业完成",
    titleEn: "Monthly review",
    goalZh: "全月学习验收，固化习惯，梳理卡点，制定下月规划。",
    tasksZh: [
      "穿搭、妆容、发型、审美成果对比",
      "日常落地检查与执行优化",
      "笔记整理归纳；内核状态梳理",
      "制定下月学习目标与计划",
    ],
  },
  {
    week: 9,
    phaseId: "p2",
    titleZh: "艺术家交流 + 审美升维",
    titleEn: "Artist dialogue",
    goalZh: "建立高阶审美认知，理解艺术与形象、内在的关联；破除审美自卑与盲从。",
    tasksZh: [
      "线下艺术家 / 设计师交流",
      "审美判断力、价值判断、独立品味逻辑",
      "破除「审美=昂贵 / 难懂」误区",
      "确立个人专属审美方向",
    ],
  },
  {
    week: 10,
    phaseId: "p2",
    titleZh: "音乐鉴赏 + 疗愈",
    titleEn: "Music & healing",
    goalZh: "用音乐滋养内在、稳定情绪、提升听觉审美。",
    tasksZh: [
      "古典、爵士、轻音乐、世界音乐、疗愈音乐入门",
      "节奏、旋律、情绪、氛围鉴赏",
      "音乐疗愈实操：减压、静心、睡眠、能量",
      "建立疗愈 / 工作 / 放松曲库",
    ],
  },
  {
    week: 11,
    phaseId: "p2",
    titleZh: "空间审美 + 设计美学",
    titleEn: "Space & design",
    goalZh: "建立空间美感，提升居家与办公环境审美，用环境滋养情绪与气质。",
    tasksZh: [
      "配色、灯光、布局、收纳、动线与氛围",
      "极简、侘寂、轻奢、东方风格认知",
      "办公与居家升级方案草案",
      "环境与情绪、能量、专注力的关系",
    ],
  },
  {
    week: 12,
    phaseId: "p2",
    titleZh: "美食审美 + 饮食搭配",
    titleEn: "Food & rituals",
    goalZh: "建立精致饮食习惯与仪式感，改善体态、皮肤与精力。",
    tasksZh: [
      "高品质餐饮审美打卡；摆盘与用餐礼仪",
      "每日饮食结构与体态管理方案",
      "仪式感饮食与自我愉悦",
      "全月复盘与作业",
    ],
  },
  {
    week: 13,
    phaseId: "p3",
    titleZh: "审美文旅定制（AA 自费）",
    titleEn: "Aesthetic travel",
    goalZh: "走出城市拓宽眼界，沉浸式感受地域文化与美学，提升格局与能量。",
    tasksZh: [
      "商议目的地（国内 / 日韩等）",
      "文化、建筑、手工艺、饮食、设计美学体验",
      "放松身心、记录素材与心境",
    ],
  },
  {
    week: 14,
    phaseId: "p3",
    titleZh: "文旅复盘 + 美学吸收",
    titleEn: "Travel debrief",
    goalZh: "将旅行体验转化为审美、气质、穿搭的实际提升。",
    tasksZh: ["行程与素材整理", "提炼穿搭与妆容新灵感", "内在能量与情绪梳理", "转化为日常动力"],
  },
  {
    week: 15,
    phaseId: "p3",
    titleZh: "朋友圈 + 个人 IP",
    titleEn: "Personal IP",
    goalZh: "建立高级、有辨识度、有质感的线上个人 IP。",
    tasksZh: [
      "微信 IP 定位、人设与风格",
      "文案结构、高级感措辞",
      "发布节奏、配图与内容框架",
      "创始人形象：审美、格局、温度、专业度",
    ],
  },
  {
    week: 16,
    phaseId: "p3",
    titleZh: "心理辅导 + 高质感沟通",
    titleEn: "Therapy & communication",
    goalZh: "破解情绪与沟通卡点，提升表达质感。（需提前整理过往经历）",
    tasksZh: [
      "1V1 心理疏导：原生家庭、自我否定、内耗",
      "高质感沟通、语言、情绪与气场",
      "清理负面认知；建立自信、稳定的沟通状态",
      "全月复盘与作业",
    ],
  },
  {
    week: 17,
    phaseId: "p4",
    titleZh: "前四个月全内容复训",
    titleEn: "4-month review",
    goalZh: "全面巩固穿搭、妆容、审美、IP、消费认知，强化落地。",
    tasksZh: ["穿搭场景模拟", "妆容发型日常化", "审美与消费练习", "朋友圈 IP 实操纠错"],
  },
  {
    week: 18,
    phaseId: "p4",
    titleZh: "实践复盘 + 成果验收",
    titleEn: "Mid-year checkpoint",
    goalZh: "固化上半年能力，明确下半年文化与情感学习方向。",
    tasksZh: ["成长复盘与对比", "习惯与效果评估", "卡点与优化方案", "下半年方向确认"],
  },
  {
    week: 19,
    phaseId: "p4",
    titleZh: "佛教基础（大乘 + 密宗）",
    titleEn: "Buddhism intro",
    goalZh: "建立正知正见，学习静心、慈悲、包容，提升内在安定。",
    tasksZh: ["基础理念与文化背景", "大乘：慈悲、利他、觉知", "密宗常识与文化", "破除迷信，理性正向认知"],
  },
  {
    week: 20,
    phaseId: "p4",
    titleZh: "心经 + 金刚经",
    titleEn: "Heart & Diamond sutras",
    goalZh: "通过经典沉淀内心力量，减少内耗，提升静定与智慧。",
    tasksZh: ["《心经》讲解与诵读", "《金刚经》核心与生活应用", "静心诵读与杂念清理", "书籍与日常诵读习惯"],
  },
  {
    week: 21,
    phaseId: "p5",
    titleZh: "拉萨 + 林芝文旅（AA 自费）",
    titleEn: "Tibet retreat",
    goalZh: "身心净化、能量提升、生命觉知；感受信仰与自然美学。",
    tasksZh: ["高原文化与信仰体验", "静心、放空、情绪清理", "一对一行程与安全保障", "记录心境与美学体验"],
  },
  {
    week: 22,
    phaseId: "p5",
    titleZh: "文旅复盘 + 修行作业",
    titleEn: "Retreat debrief",
    goalZh: "将修行旅行转化为内在稳定力与日常静心能力。",
    tasksZh: ["复盘与感悟整理", "呼吸与情绪调节日常化", "内核稳定与自控强化", "修行心得与作业"],
  },
  {
    week: 23,
    phaseId: "p5",
    titleZh: "专业摄影 + 修图",
    titleEn: "Photo & edit",
    goalZh: "掌握高级拍摄与修图，提升形象记录与视觉表达。",
    tasksZh: ["人像、风景、静物与氛围构图", "光线、角度与高级感", "修图：肤色、质感、调色", "形象照与生活美学照练习"],
  },
  {
    week: 24,
    phaseId: "p5",
    titleZh: "高级视频剪辑",
    titleEn: "Video editing",
    goalZh: "打造个人视觉 IP，提升影像表达能力。",
    tasksZh: ["剪辑基础：字幕、音乐、转场", "vlog 与美学短视频", "节奏与氛围逻辑", "个人视觉表达体系"],
  },
  {
    week: 25,
    phaseId: "p6",
    titleZh: "书籍阅读 + 深度探讨",
    titleEn: "Reading",
    goalZh: "养成阅读习惯，提升认知、思想深度与谈吐内涵。",
    tasksZh: ["阶梯式书单（成长、美学、心理、人文）", "章节提炼与观点梳理", "一对一深度探讨", "输出笔记与心得"],
  },
  {
    week: 26,
    phaseId: "p6",
    titleZh: "电影观影 + 思想延展",
    titleEn: "Film",
    goalZh: "通过电影提升审美、情商、人性认知与情绪感知力。",
    tasksZh: ["阶梯式美学 / 人性 / 成长片单", "剧情、镜头、色彩与思想拆解", "共情与审美力", "观影笔记"],
  },
  {
    week: 27,
    phaseId: "p6",
    titleZh: "播客 + 纪录片",
    titleEn: "Podcasts & docs",
    goalZh: "建立每日高效输入习惯，拓宽视野与谈吐。",
    tasksZh: ["晨间播客清单与碎片时间输入", "人文、历史、美学、心理类纪录片", "知识点与表达素材记录", "固定输入模式；可选打卡群"],
  },
  {
    week: 28,
    phaseId: "p6",
    titleZh: "全月复盘 + 作业",
    titleEn: "Input month review",
    goalZh: "固化输入习惯，输出成长成果。",
    tasksZh: ["笔记全面整理", "思想与认知复盘", "效果评估与优化", "下月学习计划"],
  },
  {
    week: 29,
    phaseId: "p7",
    titleZh: "线下社交实操 + 资源对接",
    titleEn: "Social practice",
    goalZh: "提升社交勇气与能力，链接优质圈层，学习高端社交规则。",
    tasksZh: ["真实场景陪同：破冰、对话、气场", "礼仪、姿态、语气、距离感", "资源与人脉对接", "社交自信与价值"],
  },
  {
    week: 30,
    phaseId: "p7",
    titleZh: "餐桌礼仪 + 沟通情商",
    titleEn: "Dining & EQ",
    goalZh: "掌握中西高端餐桌礼仪，提升高情商沟通与好感度。",
    tasksZh: ["入座、点餐、餐具、敬酒、交谈", "赞美、倾听、回应、分寸感", "话术、情绪与气场", "场景模拟与纠正"],
  },
  {
    week: 31,
    phaseId: "p7",
    titleZh: "茶文化 + 东方美学",
    titleEn: "Tea culture",
    goalZh: "提升东方雅致气质，理解茶与静心、社交、修养的关系。",
    tasksZh: ["茶类、产地、口感与功效", "茶馆空间与器具美学", "茶与气质、社交", "中式雅致生活审美"],
  },
  {
    week: 32,
    phaseId: "p7",
    titleZh: "泡茶 + 品茶实操",
    titleEn: "Tea practice",
    goalZh: "掌握泡茶技能，提升静心、优雅、从容的气质。",
    tasksZh: ["流程、器具、水温、出汤", "品茶、闻香、口感辨别", "以茶练习专注与情绪稳定", "全月复盘"],
  },
  {
    week: 33,
    phaseId: "p8",
    titleZh: "花卉认知 + 艺术表达",
    titleEn: "Flowers intro",
    goalZh: "认识花材与花性，学会用花卉表达情绪与审美。",
    tasksZh: ["花市 / 自然：花材、叶材、色彩", "花语、花性与女性魅力", "搭配逻辑与氛围", "与自然的审美连接"],
  },
  {
    week: 34,
    phaseId: "p8",
    titleZh: "专业插花 + 摆放",
    titleEn: "Floristry",
    goalZh: "掌握插花技能，提升仪式感与空间美感。",
    tasksZh: ["极简 / 东方 / 桌面花艺", "构图、色彩、层次、意境", "家居与办公摆放", "实操与作品"],
  },
  {
    week: 35,
    phaseId: "p8",
    titleZh: "徒步 + 禅坐 + 冥想",
    titleEn: "Hike & meditate",
    goalZh: "静心减压，提升专注、内核稳定与情绪自控。",
    tasksZh: ["轻徒步与自然放松", "禅坐姿势与呼吸", "冥想：情绪清理、能量、觉察", "建立日常静心习惯"],
  },
  {
    week: 36,
    phaseId: "p8",
    titleZh: "瑜伽 + 舞蹈形体",
    titleEn: "Yoga & poise",
    goalZh: "优化体态，提升优雅、舒展、有力量的气质。",
    tasksZh: ["瑜伽拉伸与体态矫正", "步态、站坐与肢体舒展", "柔韧与线条感", "全月复盘"],
  },
  {
    week: 37,
    phaseId: "p9",
    titleZh: "古琴文化 + 体验",
    titleEn: "Guqin",
    goalZh: "感受古琴魅力，提升静气、雅致与修养。",
    tasksZh: ["历史、乐器与美学价值", "基础指法与节奏体验", "古琴与静心、气质", "中式雅文化沉浸"],
  },
  {
    week: 38,
    phaseId: "p9",
    titleZh: "闻香 + 调香 + 香道基础",
    titleEn: "Incense",
    goalZh: "学会用香、识香、调香，提升嗅觉审美与气场。",
    tasksZh: ["线香、盘香、香薰、香器", "香气与情绪、睡眠、气场", "1V1 调香体验", "香道礼仪与生活应用"],
  },
  {
    week: 39,
    phaseId: "p9",
    titleZh: "全阶段技能复训",
    titleEn: "Life aesthetics review",
    goalZh: "巩固茶、花、香、琴、形体、冥想等生活美学技能。",
    tasksZh: ["全技能复盘与纠错", "日常化练习", "美学技能整合训练"],
  },
  {
    week: 40,
    phaseId: "p9",
    titleZh: "实践复盘 + 成果验收",
    titleEn: "Aesthetics closure",
    goalZh: "形成生活美学日常化模式，气质升级验收。",
    tasksZh: ["成果与落地检查", "内在与气质评估", "卡点与下月确认"],
  },
  {
    week: 41,
    phaseId: "p10",
    titleZh: "情绪感受力训练",
    titleEn: "Emotional awareness",
    goalZh: "提升自我与他人情绪的敏锐觉察，增强感知细腻度。",
    tasksZh: ["自我情绪识别、命名与触发点", "他人微表情、语气、肢体", "敏感度与稳定度训练", "健康觉察、少内耗"],
  },
  {
    week: 42,
    phaseId: "p10",
    titleZh: "共情与倾听",
    titleEn: "Empathy",
    goalZh: "掌握高质量倾听与共情，提升关系质量。",
    tasksZh: ["不打断、不评判、不说教", "回应、安抚与接纳", "情绪价值与陪伴力", "亲密与人际场景模拟"],
  },
  {
    week: 43,
    phaseId: "p10",
    titleZh: "情感链接能力",
    titleEn: "Deep connection",
    goalZh: "建立深度情感连接，学会表达爱、接收爱、安全感。",
    tasksZh: ["链接逻辑、真诚与温柔表达", "安全感、信任与亲密", "自我暴露与共鸣练习", "破除防御与疏离"],
  },
  {
    week: 44,
    phaseId: "p10",
    titleZh: "亲密关系基础梳理",
    titleEn: "Relationships",
    goalZh: "理解健康亲密模式，清理创伤与负面认知。",
    tasksZh: ["依恋与关系模式梳理", "创伤清理与认知纠正", "健康、平等、长久的亲密认知", "全月复盘"],
  },
  {
    week: 45,
    phaseId: "p11",
    titleZh: "性知识教育",
    titleEn: "Sexual health literacy",
    goalZh: "建立科学、健康、正向的性认知与边界尊重。",
    tasksZh: ["正向性知识学习", "自我认知与边界", "破除羞耻与错误认知", "健康成熟观念"],
  },
  {
    week: 46,
    phaseId: "p11",
    titleZh: "亲密关系技巧",
    titleEn: "Intimacy skills",
    goalZh: "提升亲密经营能力、身心和谐与幸福感。",
    tasksZh: ["氛围与身心连接", "需求表达与包容", "亲密质量与自我接纳", "全月复盘"],
  },
  {
    week: 47,
    phaseId: "p11",
    titleZh: "感恩 + 无我利他",
    titleEn: "Gratitude & giving",
    goalZh: "提升格局，减少内耗，增强幸福感与内在富足。",
    tasksZh: ["每日感恩与负面转化", "无我利他与生活应用", "放下执念与控制", "幸福感与安定感"],
  },
  {
    week: 48,
    phaseId: "p11",
    titleZh: "布施与能量回流",
    titleEn: "Generosity",
    goalZh: "建立付出心态，提升生命能量层级与格局。",
    tasksZh: ["布施与正向付出心态", "能量回流与平衡认知", "气场、格局与内在力量", "生活落地习惯"],
  },
  {
    week: 49,
    phaseId: "p11",
    titleZh: "酒文化 + 绘画艺术",
    titleEn: "Wine & painting",
    goalZh: "提升社交品味；用艺术表达情绪，实现艺术疗愈。",
    tasksZh: ["酒文化与品鉴、社交礼仪", "油画初体验与情绪表达", "释放情绪与创造力", "作品与情绪梳理"],
  },
  {
    week: 50,
    phaseId: "p11",
    titleZh: "高级语言表达 + 情商实操",
    titleEn: "Advanced expression",
    goalZh: "打造高级谈吐、精准表达、情商在线、气场强大的表达能力。",
    tasksZh: ["语言逻辑、措辞、节奏、气场", "情商与场景化实战", "创始人表达质感与说服力", "线下实操纠错"],
  },
  {
    week: 51,
    phaseId: "p11",
    titleZh: "感受爱 + 表达爱",
    titleEn: "Love",
    goalZh: "具备感受、识别、表达爱的能力，成为温暖有力量的女性。",
    tasksZh: ["感受生活中的爱与善意", "真诚表达感谢与温柔", "情绪价值与人格魅力", "爱的能力升维"],
  },
  {
    week: 52,
    phaseId: "p11",
    titleZh: "全年总结 + 复训 + 最终复盘",
    titleEn: "Year closure",
    goalZh: "完成全年闭环，复盘成果，固化能力，确立长期成长路径。",
    tasksZh: [
      "52 周内容全面复盘与对比展示",
      "技能复训、查漏补缺",
      "形象、审美、社交、情感全面评估",
      "未来长期自我成长路径",
    ],
  },
];

export function getWeek52Entry(week: number): Week52Entry | undefined {
  return WEEK52_ENTRIES.find((e) => e.week === week);
}

export function getPhaseForWeek(week: number): Week52Phase | undefined {
  return WEEK52_PHASES.find((p) => week >= p.weekStart && week <= p.weekEnd);
}
